#!/usr/bin/env python
import sys
import os.path
sys.path.append(
    os.path.abspath(os.path.join(os.path.dirname(__file__), os.path.pardir)))

import hypergrasscore

if __name__ == '__main__':
    hypergrasscore.main()

